### ISSUE TITLE
What algorithm do you use?

### ISSUE THREAD

**Issue by skaurus** [kalexmills/flownet#7]
Hey, I think it is worth documenting somewhere (maybe both in a source code and in a repo description) what algorithms do you use for solving these problems and what are their complexity.

Thanks for the project!

**Comment by skaurus** [comment]
I mean, there is lot of variations of push-relabel.

**Comment by kalexmills** [comment]
Good point -- it's been a minute since I did this project so I would definitely need to go back and review the implementation. IIRC they're straight-forward applications of techniques cobbled together from Wikipedia and Schrijver's book on Combinatorial Optimization.

**Comment by skaurus** [comment]
Yeah, a minute 😅
I was trying to get a sense of O-complexity of the used algorithm, but it looks like there is no ready answer. I'll close my issue then. Thanks!
